apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    helm:
      skipCrds: true
      values:  |

        experimental:
          otlpLogs: true
          plugins:
            traefikoidc:
              moduleName: "github.com/lukaszraczylo/traefikoidc"
              version: "v0.8.10"

        deployment:
          kind: DaemonSet

        providers:
          kubernetesCRD:
            allowExternalNameServices: true
          kubernetesIngress:
            publishedService:
              enabled: true     #if you want to use with kubernetes ingress, set it to true.
          kubernetesGateway:
            enabled: true
            statusAddress:
              service:
                enabled: true

        gateway:
          annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
                cert-manager.io/secret-template: |
                   {"annotations": {"reflector.v1.k8s.emberstack.com/reflection-allowed": "true"}}
                external-dns.alpha.kubernetes.io/target: 7c6ce3b1-97d9-4ac3-aefa-516c85871114.cfargotunnel.com
          listeners:
            web:           # HTTP listener that matches entryPoint `web`
              port: 8000
              protocol: HTTP
              hostname: "*.kylebrighton.com"
              namespacePolicy:
                from: All
              forwardedHeaders:
                trustedIPs:
                  - 127.0.0.1/32
                  - 172.20.0.0/24
                  - 173.245.48.0/20
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 141.101.64.0/18
                  - 108.162.192.0/18
                  - 190.93.240.0/20
                  - 188.114.96.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17
                  - 162.158.0.0/15
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 172.64.0.0/13
                  - 131.0.72.0/22
                  - '2400:cb00::/32'
                  - '2606:4700::/32'
                  - '2803:f800::/32'
                  - '2405:b500::/32'
                  - '2405:8100::/32'
                  - '2a06:98c0::/29'
                  - '2c0f:f248::/32'


            websecure:         # HTTPS listener that matches entryPoint `websecure`
              port: 8443
              protocol: HTTPS  # TLS terminates inside Traefik
              hostname: "*.kylebrighton.com"
              namespacePolicy:
                from: All
              mode: Terminate
              certificateRefs:
                - name: traefik-tls  # the Secret we created before the installation

        logs:
          general:
            otlp:
              enabled: true
              http:
                enabled: true
                endpoint: "http://grafana-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4318"

          # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
          access:
            enabled: true
            otlp:
              enabled: true
              http:
                enabled: true
                endpoint: "http://grafana-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4318"


        # Enables Prometheus for Metrics
        metrics:
          prometheus:
            enabled: true
            service:
              enabled: true
            serviceMonitor:
              enabled: true
        tracing:
          otlp:
            enabled: true
            http:
              enabled: true
              endpoint: "http://grafana-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4318"

        ingressRoute:
          dashboard:
            enabled: true
            entryPoints:
              - web
              - websecure

        service:
          enabled: true
          spec:
            externalTrafficPolicy: Local
          annotations:
            service.beta.kubernetes.io/metal-lb: "true"
            metallb.io/address-pool: first-pool # Optional: If using MetalLB
          type: LoadBalancer # Change to LoadBalancer if using MetalLB
          ports:
            web:
              port: 80
              targetPort: 80
            websecure:
              port: 443
              targetPort: 443

        # Additional configuration for dashboard access
        dashboard:
          enabled: true
          ingress:
            enabled: true
            path: /dashboard/
            pathType: Prefix
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - host: "dashboard.kylebrighton.com" #traefik.example.com  # Change to your desired host
                paths:
                  - /

    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.4.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
